name: C Program Build and Release
# GitHub Actions　のワークフロー構文
# https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C compiler
        run: sudo apt-get install -y build-essential

      - name: Build the C program
        run: |
          gcc -o my_program my_program.c

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        # https://github.com/softprops/action-gh-release
        with:
          tag_name: v1.0.0
          # tag_name: Name of a tag. defaults to github.ref_nameName of a tag. defaults to github.ref_name
          files: my_program
          # files: Newline-delimited globs of paths to assets to upload for release
          # https://github.com/softprops/action-gh-release?tab=readme-ov-file#inputs
        env:
          # https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions#env
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GitHub によって、ワークフローで使用する一意の GITHUB_TOKEN シークレットが自動的に作成されます。
          # https://docs.github.com/ja/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret
